# ----- Variational Auto-Encoder ----------------------------------
_target_: autoencoders.models.vae.VAE
name: vae
latent_dim: 8
hidden_dims: [32, 16]
dropout: [0.3, 0.1]
recon_weight: 1.0
kl_weight: 0.05


# # ----- Debug ----------------------------------
# _target_: autoencoders.models.vae.VAE
# name: vae
# latent_dim: 2
# hidden_dims: [8, 4]
# dropout: [0.3, 0.2]
# recon_weight: 1.0
# kl_weight: 0.01


